import React, { useEffect } from 'react';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ROUTE } from '../utils/constants';
import '../utils/i18n';

const Index = () => {
  const router = useRouter();
  useEffect(() => {
    router.push(ROUTE?.home);
  }, []);

  return (
    <Head>
      <title>Type Game</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Index;
